### ISSUE TITLE
Vorgehensbeschreibung Chronologisch

### ISSUE THREAD

**Issue by MartinEnders** [quicktus/how2conference#5]
Super wäre noch wenn die Checkliste chronologisch aufgebaut ist (ist sie glaube ich eh schon -> vielleicht noch explizit hinschreiben) und zu den einzelnen Aufgaben Templates (da hast du ja schon einiges in den Ordnern) verlinkt werden.

**Comment by quicktus** [comment]
Auf dem wip branch erledigt. Wenn alle Issues geschlossen sind merge ich wip auf main.
