### ISSUE TITLE
Code Doku

### ISSUE THREAD

**Issue by MartinEnders** [quicktus/how2conference#6]
Hier vielleicht noch ein paar Kommentare einfügen und ne kurze Beschreibung wie man das zum laufen bekommt und wie man das verwendet:

https://github.com/quicktus/how2conference/blob/0714330e98e479465553402998f238108346ba4f/3.%20Abgabe%20der%20Reviews/Paper_assignment.java

**Comment by quicktus** [comment]
Ich habe jetzt mehr Kommentare eingefügt. Damit sollte man den code verwenden ung gegebenenfalls anpassen/ erweitern können. 
Da es hier um eine einfache .java geht habe ich keine Beschreibung wie man das zum laufen bekommt hinzugefügt. Das sollte man eigentlich wissen wenn man WInf studiert. Es wird ja nichts besonderes eingebunden oder so ... 

Java falls nötig installieren,
Datei mit IDE der Wahl öffnen -> run klicken

Alternativ:
mit vim etc. bearbeiten,
mit javac kompilieren
und anschließend ausführen.

Wer das nicht von selbst schafft wird mit dem code auch nichst anfangen können.

Falls die Kommentare zu dünn sind oder How2install Java trotzdem gewünscht ist einfach das Issue neu aufmachen oder neues erstellen.
